# Generated by Django 2.2.6 on 2019-12-02 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='scholarship_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(default='', max_length=50)),
                ('school', models.CharField(default='', max_length=50)),
                ('grade', models.CharField(default='', max_length=50)),
                ('year', models.CharField(default='', max_length=50)),
                ('credit', models.CharField(default='', max_length=50)),
                ('income', models.IntegerField(blank=True, null=True)),
                ('impaired', models.CharField(default='', max_length=10)),
                ('merit', models.CharField(default='', max_length=10)),
                ('major', models.CharField(default='', max_length=50)),
                ('regular_decision', models.CharField(default='', max_length=10)),
            ],
        ),
    ]
