# Generated by Django 2.1 on 2019-11-29 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_contest',
            name='contest_type',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
