# Generated by Django 2.1 on 2019-11-29 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_user_contest_contest_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_contest',
            name='contest_type',
        ),
    ]
