# Generated by Django 2.1 on 2019-12-02 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0004_user_scholarship'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User_Contest',
        ),
    ]
