# Generated by Django 2.1 on 2019-12-02 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0005_delete_user_contest'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Contest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(default='', max_length=50)),
                ('contest_id', models.CharField(default='', max_length=50)),
            ],
        ),
    ]
